const cache=new Map();
async function get(url){if(cache.has(url))return cache.get(url);const saved=sessionStorage.getItem(url);if(saved){const d=JSON.parse(saved);cache.set(url,d);return d}const r=await fetch(url);if(!r.ok)throw Error('PokéAPI indisponível');const d=await r.json();cache.set(url,d);try{sessionStorage.setItem(url,JSON.stringify(d))}catch{}return d}
export async function pokemon(id){const d=await get(`https://pokeapi.co/api/v2/pokemon/${id}`);const species=await get(d.species.url);const moves=d.moves.map(m=>{const versions=m.version_group_details.filter(v=>v.move_learn_method.name==='level-up'&&v.level_learned_at>0),latest=versions.at(-1);return latest?{name:m.move.name,url:m.move.url,level:latest.level_learned_at}:null}).filter(Boolean).sort((a,b)=>a.level-b.level);return{id:d.id,name:title(d.name),types:d.types.map(x=>x.type.name),hp:d.stats[0].base_stat,attack:d.stats[1].base_stat,defense:d.stats[2].base_stat,rarity:Math.max(.08,Math.min(.9,species.capture_rate/255)),cry:d.cries?.latest||d.cries?.legacy||null,moves}}
export async function move(url){const d=await get(url);return{name:title(d.name),type:d.type.name,power:d.power??0,accuracy:d.accuracy??100,damageClass:d.damage_class.name}}
export async function typeChart(type){const d=await get(`https://pokeapi.co/api/v2/type/${type}`),r=d.damage_relations;return{double:r.double_damage_to.map(x=>x.name),half:r.half_damage_to.map(x=>x.name),none:r.no_damage_to.map(x=>x.name)}}
export async function movesFor(p){const data=await pokemon(p.id),learned=data.moves.filter(m=>m.level<=p.level);return Promise.all((learned.length?learned.slice(-12):data.moves.slice(0,1)).map(async m=>({...m,...await move(m.url)})))}
const title=s=>s.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ');
export async function weather(lat,lon){const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,weather_code,is_day&timezone=auto`);if(!r.ok)throw Error();const c=(await r.json()).current;return{code:c.weather_code,temp:Math.round(c.temperature_2m),...weatherLabel(c.weather_code),day:!!c.is_day,source:'local'}}
export function weatherLabel(code){if(code<=1)return{label:'Céu limpo',icon:'clear'};if(code<=3)return{label:'Nublado',icon:'cloudy'};if(code<=48)return{label:'Neblina',icon:'fog'};if(code<=67)return{label:'Chuva',icon:'rain'};if(code<=77)return{label:'Neve',icon:'snow'};if(code<=82)return{label:'Pancadas',icon:'rain'};return{label:'Tempestade',icon:'storm'}}
export function requestWeather(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject();navigator.geolocation.getCurrentPosition(async p=>{try{resolve(await weather(p.coords.latitude,p.coords.longitude))}catch{reject()}},reject,{timeout:7000,maximumAge:1800000})})}
