const cache=new Map();
async function get(url){if(cache.has(url))return cache.get(url);const saved=sessionStorage.getItem(url);if(saved){const d=JSON.parse(saved);cache.set(url,d);return d}const r=await fetch(url);if(!r.ok)throw Error('PokéAPI indisponível');const d=await r.json();cache.set(url,d);try{sessionStorage.setItem(url,JSON.stringify(d))}catch{}return d}
export async function pokemon(id){const d=await get(`https://pokeapi.co/api/v2/pokemon/${id}`);const species=await get(d.species.url);const moves=d.moves.map(m=>{const versions=m.version_group_details.filter(v=>v.move_learn_method.name==='level-up'&&v.level_learned_at>0),latest=versions.at(-1);return latest?{name:m.move.name,url:m.move.url,level:latest.level_learned_at}:null}).filter(Boolean).sort((a,b)=>a.level-b.level);return{id:d.id,name:title(d.name),types:d.types.map(x=>x.type.name),genderRate:species.gender_rate,eggGroups:species.egg_groups.map(x=>x.name),hp:d.stats[0].base_stat,attack:d.stats[1].base_stat,defense:d.stats[2].base_stat,baseExperience:d.base_experience||50,rarity:Math.max(.08,Math.min(.9,species.capture_rate/255)),cry:d.cries?.latest||d.cries?.legacy||null,moves}}
export async function move(url){const d=await get(url);return{name:title(d.name),type:d.type.name,power:d.power??0,accuracy:d.accuracy??100,damageClass:d.damage_class.name}}
export async function typeChart(type){const d=await get(`https://pokeapi.co/api/v2/type/${type}`),r=d.damage_relations;return{double:r.double_damage_to.map(x=>x.name),half:r.half_damage_to.map(x=>x.name),none:r.no_damage_to.map(x=>x.name)}}
export async function movesFor(p){const data=await pokemon(p.id),learned=data.moves.filter(m=>m.level<=p.level);return Promise.all((learned.length?learned.slice(-12):data.moves.slice(0,1)).map(async m=>({...m,...await move(m.url)})))}
const resourceId=url=>Number(url?.match(/\/(\d+)\/?$/)?.[1]);
export async function evolutionOptions(id){if(Number(id)===133)return[{id:134,name:'Vaporeon',trigger:'use-item',item:'water-stone'},{id:135,name:'Jolteon',trigger:'use-item',item:'thunder-stone'},{id:136,name:'Flareon',trigger:'use-item',item:'fire-stone'},{id:470,name:'Leafeon',trigger:'use-item',item:'leaf-stone'},{id:471,name:'Glaceon',trigger:'use-item',item:'ice-stone'},{id:196,name:'Espeon',trigger:'special',minLevel:25,minHappiness:80,timeOfDay:'day'},{id:197,name:'Umbreon',trigger:'special',minLevel:25,minHappiness:80,timeOfDay:'night'},{id:700,name:'Sylveon',trigger:'special',minLevel:25,minHappiness:80,knownMoveType:'fairy'}];const form=await get(`https://pokeapi.co/api/v2/pokemon/${id}`),species=await get(form.species.url),chain=await get(species.evolution_chain.url);let current=null;const walk=node=>{if(resourceId(node.species.url)===species.id)current=node;else node.evolves_to.forEach(walk)};walk(chain.chain);return(current?.evolves_to||[]).flatMap(next=>(next.evolution_details?.length?next.evolution_details:[{}]).map(d=>{const rawTrigger=d.trigger?.name||'unknown',item=d.item?.name||null,special=!item&&(rawTrigger==='trade'||d.min_happiness!==null||d.min_affection!==null||d.known_move||d.known_move_type||d.location||d.needs_overworld_rain||d.turn_upside_down||d.time_of_day||d.relative_physical_stats!==null&&d.relative_physical_stats!==undefined);return{id:resourceId(next.species.url),name:title(next.species.name),trigger:item?'use-item':'level-up',minLevel:special?35:d.min_level??(item?null:35),item,minHappiness:d.min_happiness??null,timeOfDay:d.time_of_day||null,special}})) }
const title=s=>s.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ');
export async function weather(lat,lon){const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,weather_code,is_day&timezone=auto`);if(!r.ok)throw Error();const c=(await r.json()).current;return{code:c.weather_code,temp:Math.round(c.temperature_2m),...weatherLabel(c.weather_code),day:!!c.is_day,source:'local'}}
export function weatherLabel(code){if(code<=1)return{label:'Céu limpo',icon:'clear'};if(code<=3)return{label:'Nublado',icon:'cloudy'};if(code<=48)return{label:'Neblina',icon:'fog'};if(code<=67)return{label:'Chuva',icon:'rain'};if(code<=77)return{label:'Neve',icon:'snow'};if(code<=82)return{label:'Pancadas',icon:'rain'};return{label:'Tempestade',icon:'storm'}}
export function requestWeather(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject();navigator.geolocation.getCurrentPosition(async p=>{try{resolve(await weather(p.coords.latitude,p.coords.longitude))}catch{reject()}},reject,{timeout:7000,maximumAge:1800000})})}
