import{STARTERS,POKEMON_NAMES,EVOLUTIONS,ITEMS,SHOP,WILD_POOL,LEADERS,GAME_COSTS,sprite,itemSprite,coinSprite}from'./data.js';
import{load,save,clear,fresh,applyOffline,addCreature}from'./storage.js';
import{pokemon,movesFor,typeChart,requestWeather}from'./api.js';
import{berryGame,memoryGame,timingGame}from'./games.js';
let state=load(),selected=null,currentView='home',battle=null,toastTimer,shopFilter='all';
const $=s=>document.querySelector(s),clamp=n=>Math.max(0,Math.min(100,n)),fmt=s=>s.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ');
const itemImg=(id,alt='')=>`<img class="item-pixel" src="${itemSprite(id)}" alt="${alt}">`;
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}
function persist(){save(state);updateResources()}
function updateResources(){if(!state)return;$('#coins-value').textContent=Math.floor(state.coins);$('#balls-value').textContent=['poke-ball','great-ball','ultra-ball'].reduce((n,id)=>n+(state.inventory[id]||0),0)}
function starters(){const grid=$('#starter-grid');grid.innerHTML=STARTERS.map(id=>`<button class="starter-card" data-id="${id}"><img src="${sprite(id)}" alt=""><b>${POKEMON_NAMES[id]}</b></button>`).join('');grid.onclick=e=>{const c=e.target.closest('.starter-card');if(!c)return;selected=+c.dataset.id;grid.querySelectorAll('.starter-card').forEach(x=>x.classList.toggle('selected',x===c));$('#starter-count').textContent=`${STARTERS.indexOf(selected)+1} / 11`;$('#nickname-input').placeholder=POKEMON_NAMES[selected];$('#start-button').disabled=false};$('#start-button').onclick=()=>{const name=$('#nickname-input').value.trim()||POKEMON_NAMES[selected];state=fresh(selected,name,POKEMON_NAMES[selected]);persist();enterGame();toast(`Bem-vindo ao Pokégotchi, ${name}!`)}}
function showTitle(){const has=!!state,p=state?.pokemon;$('#title-screen').classList.remove('hidden');$('#starter-screen').classList.add('hidden');$('#game-screen').classList.add('hidden');$('#continue-button').disabled=!has;$('#save-summary').textContent=has?`${p.nickname} · ${p.name} · Nv. ${p.level} · ${state.caught.length} espécies`:'Nenhuma jornada encontrada.';$('#continue-button').onclick=()=>enterGame();$('#changelog-button').onclick=showChangelog;$('#new-game-button').onclick=()=>{if(state&&!confirm('Começar uma nova jornada apagará permanentemente o save atual. Deseja continuar?'))return;if(state)clear();state=null;selected=null;$('#title-screen').classList.add('hidden');$('#starter-screen').classList.remove('hidden');starters()}}
function enterGame(){const mins=applyOffline(state);$('#title-screen').classList.add('hidden');$('#starter-screen').classList.add('hidden');$('#game-screen').classList.remove('hidden');setupNav();updateResources();generateOfflineEncounters();render(currentView);if(mins)toast(`Enquanto você saiu, ${mins} min se passaram.`);updateWeather()}
function setupNav(){$('.sidebar')?.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;currentView=b.dataset.view;document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n===b));render(currentView)});$('#settings-button').onclick=settings}
function render(v){generateOfflineEncounters();({home,yard,games,shop,inventory,rooms,dex,battle:battleView}[v]||home)();updateResources()}
function stat(icon,label,value,color){return`<div class="stat-row"><span class="pixel-label">${icon}</span><span>${label}</span><div class="stat-track"><div class="stat-fill" style="width:${clamp(value)}%;background:${color}"></div></div><b>${Math.round(value)}</b></div>`}
function weatherMark(){return`<span class="weather-mark ${state.weather.icon}">${state.weather.icon==='rain'?'///':state.weather.icon==='storm'?'ZAP':state.weather.icon==='cloudy'?'CLOUD':state.weather.icon==='snow'?'***':'SUN'}</span>`}
function home(){const p=state.pokemon,w=state.weather,sleeping=!!p.sleepingSince,need=sleeping?'Z Z Z...':p.hunger<35?'Estou com fome!':p.energy<30?'Preciso dormir...':p.happiness<35?'Vamos brincar?':'Que bom ver você!';$('#view-container').innerHTML=`<div class="view-title"><div><h1>Olá, treinador!</h1><p>Seu parceiro está ${sleeping?'descansando':'feliz em ver você'}.</p></div><span>${new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</span></div><div class="home-grid"><div class="room ${w.day?'':'night'}"><div class="weather-badge">${weatherMark()} ${w.label}${w.temp!==null?' · '+w.temp+'°C':''}</div><div class="window"></div><div class="pet-stage"><div class="pet-bubble">${need}</div><img class="pet-sprite ${sleeping?'sleeping':''}" src="${sprite(p.id)}" alt="${p.nickname}"><div class="pet-shadow"></div></div><div class="room-actions"><button class="action-button" data-act="food">${itemImg('oran-berry')}Alimentar</button><button class="action-button" data-act="play">${itemImg('poke-doll')}Brincar</button><button class="action-button" data-act="sleep">${itemImg('leftovers')}${sleeping?'Acordar':'Dormir'}</button><button class="action-button" data-act="clean">${itemImg('rage-candy-bar')}Limpar</button></div></div><div class="side-stack"><div class="profile-card"><div class="pet-id"><div><small>${p.name.toUpperCase()}</small><h2>${p.nickname}</h2></div><span class="level-pill">NV. ${p.level}</span></div><small>${p.xp} / ${p.level*45} XP</small><div class="xp-track"><div class="xp-fill" style="width:${p.xp/(p.level*45)*100}%"></div></div><div class="stats">${stat('HP','Saúde',p.health,'#df3f47')}${stat('FO','Fome',p.hunger,'#d19b43')}${stat('EN','Energia',p.energy,'#3e80b6')}${stat('FE','Felicidade',p.happiness,'#a65fc0')}${stat('HI','Higiene',p.hygiene,'#62a84c')}</div>${sleeping?`<div class="sleep-note">Carga completa em aproximadamente ${sleepRemaining(p)}.</div>`:''}</div><div class="daily-note"><h3>Presente diário</h3><p>PokéCoins e um item surpresa por dia.</p><button id="daily">Resgatar presente</button></div></div></div>`;$('#view-container').onclick=e=>{const a=e.target.closest('[data-act]');if(a)care(a.dataset.act)};$('#daily').onclick=daily}
function sleepRemaining(p){const left=Math.max(0,(100-p.energy)*288000);const h=Math.floor(left/3600000),m=Math.ceil(left%3600000/60000);return`${h}h ${m}min`}
function care(type){const p=state.pokemon;if(type==='sleep'){if(p.sleepingSince){updateSleeping(p);p.sleepingSince=null;toast(`${p.nickname} acordou com ${Math.round(p.energy)} de energia.`)}else{p.sleepingSince=Date.now();toast(`${p.nickname} começou a dormir. Energia cheia em até 8h.`)}persist();return home()}if(p.sleepingSince)return toast('Acorde seu Pokémon primeiro.');openItemPicker(type)}
function openItemPicker(type){const available=ITEMS.filter(i=>i.type===type&&(state.inventory[i.id]||0)>0),m=$('#modal');$('#modal-content').innerHTML=`<h2>${{food:'Alimentar',play:'Brincar',clean:'Limpar'}[type]}</h2><p>Escolha um item da mochila.</p><div class="picker-grid">${available.map(i=>`<button class="pick-item" data-use="${i.id}">${itemImg(i.id,i.name)}<b>${i.name}</b><small>×${state.inventory[i.id]}</small></button>`).join('')||'<p>Nenhum item disponível. Visite a loja.</p>'}</div>`;m.showModal();m.onclick=e=>{const b=e.target.closest('[data-use]');if(b)useItem(b.dataset.use)}}
function useItem(id){const i=ITEMS.find(x=>x.id===id),p=state.pokemon;if(!i||!state.inventory[id])return;state.inventory[id]--;if(i.type==='food'){p.hunger=clamp(p.hunger+i.value);p.health=clamp(p.health+5)}if(i.type==='play')p.happiness=clamp(p.happiness+i.value);if(i.type==='clean')p.hygiene=clamp(p.hygiene+i.value);persist();$('#modal').close();home();toast(`${i.name} utilizado.`)}
function updateSleeping(p){if(!p.sleepingSince)return;p.energy=clamp(p.energy+(Date.now()-Math.max(p.sleepingSince,state.lastSaved||p.sleepingSince))/288000);if(p.energy>=100)p.sleepingSince=null}
function daily(){const today=new Date().toDateString();if(state.dailyClaim===today)return toast('Você já resgatou o presente de hoje.');const pool=['oran-berry','sitrus-berry','poke-ball','poke-doll','soap'],id=pool[Math.floor(Math.random()*pool.length)],qty=id==='poke-ball'?2:1;state.dailyClaim=today;state.coins+=50;state.inventory[id]=(state.inventory[id]||0)+qty;persist();home();toast(`50 PokéCoins e ${qty} ${ITEMS.find(i=>i.id===id).name}!`)}
async function updateWeather(){try{state.weather=await requestWeather();persist();if(currentView==='home')home()}catch{const h=new Date().getHours();state.weather.day=h>=6&&h<18;state.weather.source='estimado';persist()}}
function generateOfflineEncounters(){const now=Date.now();state.encounters=state.encounters||[];while(now>=state.nextSpawn&&state.encounters.length<8){const id=WILD_POOL[Math.floor(Math.random()*WILD_POOL.length)],rarity=Math.random();state.encounters.push({id,appearedAt:state.nextSpawn,rarity:rarity>.92?.15:rarity>.7?.35:.65,fed:null});state.seen=[...new Set([...state.seen,id])];state.nextSpawn+=randSpawn()}if(now>=state.nextSpawn&&state.encounters.length>=8)state.nextSpawn=now+randSpawn();persist();$('#spawn-dot')?.classList.toggle('show',state.encounters.length>0)}
const randSpawn=()=>600000+Math.random()*10200000;
async function yard(){generateOfflineEncounters();const min=Math.max(1,Math.ceil((state.nextSpawn-Date.now())/60000));$('#view-container').innerHTML=`<div class="view-title"><div><h1>Quintal</h1><p>Visitantes ficam registrados até você escolher um.</p></div><span>Próximo: ${min} min</span></div>${state.encounters.length?`<div class="encounter-grid">${state.encounters.map((e,i)=>`<button class="encounter-card" data-enc="${i}"><img src="${sprite(e.id)}" alt=""><b>Pokémon #${e.id}</b><small>${e.rarity<.2?'Muito raro':e.rarity<.5?'Raro':'Comum'}</small></button>`).join('')}</div><p class="warning-box">Escolha com cuidado: ao iniciar uma tentativa, os outros visitantes irão embora.</p>`:`<div class="yard-scene"><div class="wild-card"><img class="item-pixel empty-yard" src="${itemSprite('honey')}" alt=""><h2>Nenhum visitante agora</h2><p>Novos rastros podem aparecer entre 10 min e 3 h.</p></div></div>`}`;$('#view-container').onclick=e=>{const b=e.target.closest('[data-enc]');if(b)captureEncounter(+b.dataset.enc)}}
async function captureEncounter(index){const enc=state.encounters[index];let info;try{info=await pokemon(enc.id)}catch{return toast('Não foi possível consultar este Pokémon.')}enc.name=info.name;enc.types=info.types;enc.rarity=Math.min(Number.isFinite(enc.rarity)?enc.rarity:.5,info.rarity);state.encounters=[enc];persist();drawCapture(enc)}
function drawCapture(e){const berries=ITEMS.filter(i=>i.type==='food'&&(state.inventory[i.id]||0)),balls=ITEMS.filter(i=>i.type==='ball'&&(state.inventory[i.id]||0));$('#view-container').innerHTML=`<div class="view-title"><div><h1>Encontro selvagem</h1><p>${e.name} · ${e.types.map(fmt).join(' / ')} · ${e.rarity<.2?'Muito raro':e.rarity<.5?'Raro':'Comum'}</p></div></div><div class="capture-layout"><div class="yard-scene"><div class="wild-card"><div class="capture-ring"></div><img src="${sprite(e.id)}" alt="${e.name}"><h2>${e.name}</h2><p>${e.fed?`Comeu ${ITEMS.find(i=>i.id===e.fed)?.name}.`:'Você pode oferecer uma berry antes de lançar.'}</p></div></div><div class="capture-tools"><div class="panel"><h3>Berries</h3><div class="tool-row">${berries.map(i=>`<button data-feed="${i.id}" ${e.fed?'disabled':''}>${itemImg(i.id)}<small>×${state.inventory[i.id]}</small></button>`).join('')||'Sem berries'}</div></div><div class="panel"><h3>Pokébolas</h3><div class="tool-row">${balls.map(i=>`<button data-ball="${i.id}">${itemImg(i.id)}<small>${i.name} ×${state.inventory[i.id]}</small></button>`).join('')||'Sem Pokébolas'}</div></div><button class="secondary-button" id="leave-enc">Deixar ir</button></div></div>`;$('#view-container').onclick=ev=>{const f=ev.target.closest('[data-feed]'),b=ev.target.closest('[data-ball]');if(f)feedWild(e,f.dataset.feed);if(b)throwBall(e,b.dataset.ball)};$('#leave-enc').onclick=()=>{state.encounters=[];state.nextSpawn=Date.now()+randSpawn();persist();yard()}}
function feedWild(e,id){if(!state.inventory[id])return;state.inventory[id]--;e.fed=id;persist();const favored=ITEMS.find(i=>i.id===id).favored.some(t=>e.types.includes(t));toast(favored?`${e.name} adorou esta berry!`:`${e.name} aceitou a berry.`);drawCapture(e)}
async function throwBall(e,id){const ball=ITEMS.find(i=>i.id===id);if(!state.inventory[id])return;state.inventory[id]--;const berry=e.fed?ITEMS.find(i=>i.id===e.fed):null,favored=berry?.favored?.some(t=>(e.types||[]).includes(t)),rarity=Number.isFinite(e.rarity)?e.rarity:.35,chance=Math.min(.94,rarity*ball.catch*(favored?1.45:e.fed?1.15:1));persist();toast(`${ball.name} lançada...`);await new Promise(r=>setTimeout(r,900));if(Math.random()<chance)nicknameCapture(e);else{toast(`${e.name} escapou. Chance estimada: ${Math.round(chance*100)}%`);drawCapture(e)}}
function nicknameCapture(e){const m=$('#modal');$('#modal-content').innerHTML=`<div class="capture-success"><img src="${sprite(e.id)}" alt="${e.name}"><h2>${e.name} foi capturado!</h2><label class="name-field">Deseja dar um apelido?<input id="caught-nickname" maxlength="14" value="${e.name}" aria-label="Apelido do Pokémon"></label><button class="primary-button" id="confirm-nickname">Confirmar apelido <span>▶</span></button></div>`;m.showModal();$('#confirm-nickname').onclick=()=>{const nickname=$('#caught-nickname').value.trim()||e.name,p=addCreature(state,e,nickname);state.encounters=[];state.nextSpawn=Date.now()+randSpawn();persist();m.close();toast(`${nickname} foi enviado para ${state.active.includes(p)?'um quarto':'a Box'}!`);rooms()}}
function games(){$('#view-container').innerHTML=`<div class="view-title"><div><h1>Arcade</h1><p>Minigames gastam energia do Pokémon principal.</p></div><span>Energia: ${Math.round(state.pokemon.energy)}</span></div><div class="cards-grid">${[['oran-berry','Pegar Berries','Colete frutas antes que caiam.','berry'],['vs-recorder','Memória Pokémon','Encontre todos os pares.','memory'],['quick-claw','Treino de Ataque','Acerte a faixa verde.','timing']].map(g=>`<article class="game-card"><div class="game-icon">${itemImg(g[0])}</div><h3>${g[1]}</h3><p>${g[2]}</p><b>Custo: ${GAME_COSTS[g[3]]} energia</b><button class="secondary-button" data-game="${g[3]}" ${state.pokemon.energy<GAME_COSTS[g[3]]||state.pokemon.sleepingSince?'disabled':''}>${state.pokemon.sleepingSince?'Dormindo':'Jogar agora'}</button></article>`).join('')}</div>`;$('#view-container').onclick=e=>{const b=e.target.closest('[data-game]');if(b)openGame(b.dataset.game)}}
function openGame(type){const cost=GAME_COSTS[type],p=state.pokemon;if(p.sleepingSince)return toast('Seu Pokémon está dormindo.');if(p.energy<cost)return toast(`Você precisa de ${cost} de energia.`);p.energy-=cost;persist();const m=$('#modal'),root=$('#modal-content'),finish=(xp,coins,msg)=>{gainXp(xp);state.coins+=coins;p.happiness=clamp(p.happiness+8);persist();root.innerHTML=`<div class="game-area">${itemImg('nugget')}<h2>${msg}</h2><p>+${xp} XP · +${coins} PokéCoins · -${cost} energia</p><button class="primary-button" id="game-done">Continuar</button></div>`;$('#game-done').onclick=()=>m.close()};({berry:berryGame,memory:memoryGame,timing:timingGame}[type])(root,finish);m.showModal()}
function gainXp(xp){const p=state.pokemon,bonus=state.furniture.reduce((n,id)=>n+(ITEMS.find(i=>i.id===id)?.expBonus||0),0);p.xp+=Math.round(xp*(1+bonus));while(p.xp>=p.level*45){p.xp-=p.level*45;p.level++;const ev=EVOLUTIONS[p.id];if(ev?.level&&p.level>=ev.level){p.id=ev.to;p.name=ev.name;state.caught=[...new Set([...state.caught,p.id])]}refreshMoves(p)}}
async function refreshMoves(p){try{const all=await movesFor(p);if(!p.moves?.length)p.moves=all.slice(-4).map(m=>m.name);persist()}catch{}}
function inventory(){$('#view-container').innerHTML=`<div class="view-title"><div><h1>Mochila</h1><p>Consumíveis, Pokébolas e itens especiais.</p></div></div><div class="inventory-grid">${ITEMS.filter(i=>(state.inventory[i.id]||0)>0).map(i=>`<article class="inventory-card">${itemImg(i.id,i.name)}<div><h3>${i.name}</h3><p>${i.desc}</p></div><b>×${state.inventory[i.id]}</b></article>`).join('')||'<p>Sua mochila está vazia.</p>'}</div>`}
function shopCategory(i){return i.type==='food'?'berries':i.type==='evolution'?'evolution':i.type==='furniture'?'furniture':i.type==='ball'?'capture':'care'}
function shop(){const filtered=shopFilter==='all'?SHOP:SHOP.filter(i=>shopCategory(i)===shopFilter);$('#view-container').innerHTML=`<div class="view-title"><div><h1>PokéMart</h1><p>Itens oficiais e melhorias para os quartos.</p></div><b><img class="tiny-item" src="${coinSprite}" alt=""> ${Math.floor(state.coins)}</b></div><div class="shop-filters">${[['all','Todos'],['berries','Berries'],['capture','Captura'],['care','Cuidados'],['evolution','Evolução'],['furniture','Móveis']].map(([id,n])=>`<button class="${shopFilter===id?'active':''}" data-filter="${id}">${n}</button>`).join('')}</div><div class="shop-layout"><div class="shop-grid">${filtered.map(i=>`<article class="shop-card">${itemImg(i.id,i.name)}<h3>${i.name}</h3><p>${i.type==='food'?`${i.desc}. Pode alimentar seu Pokémon (+${i.value} fome).`:i.desc}</p><div class="price"><b>${i.price} PC</b><button data-buy="${i.id}">Comprar</button></div></article>`).join('')}</div><aside class="panel"><h3>Resumo</h3><p>${Object.values(state.inventory).reduce((a,b)=>a+b,0)} itens na mochila.</p><p>${state.furniture.length} móveis instalados.</p><p>Bônus de EXP: +${Math.round(state.furniture.reduce((n,id)=>n+(ITEMS.find(i=>i.id===id)?.expBonus||0),0)*100)}%</p></aside></div>`;$('#view-container').onclick=e=>{const f=e.target.closest('[data-filter]'),b=e.target.closest('[data-buy]');if(f){shopFilter=f.dataset.filter;return shop()}if(b)buy(b.dataset.buy)}}
function buy(id){const i=ITEMS.find(x=>x.id===id);if(state.coins<i.price)return toast('PokéCoins insuficientes.');if(i.type==='furniture'&&state.furniture.includes(id))return toast('Esse móvel já está instalado.');state.coins-=i.price;if(i.type==='furniture')state.furniture.push(id);else state.inventory[id]=(state.inventory[id]||0)+1;persist();shop();toast(`${i.name} adquirido!`);tryEvolution(id)}
function tryEvolution(item){const p=state.pokemon,ev=EVOLUTIONS[p.id];if(ev?.item===item&&state.inventory[item]){state.inventory[item]--;p.id=ev.to;p.name=ev.name;state.caught=[...new Set([...state.caught,p.id])];persist();toast(`${p.nickname} evoluiu para ${ev.name}!`)}}
function rooms(){$('#view-container').innerHTML=`<div class="view-title"><div><h1>Quartos & Boxes</h1><p>Até seis Pokémon ativos. Clique para torná-lo seu parceiro principal.</p></div><span>${state.active.length}/6 ativos</span></div><h2 class="section-label">Quartos ativos</h2><div class="rooms-grid">${state.active.map((p,i)=>pokeRoom(p,i)).join('')}${state.active.length<6?`<div class="empty-room">QUARTO LIVRE</div>`:''}</div><h2 class="section-label">Box Pokémon</h2><div class="box-grid">${state.boxes.map((p,i)=>`<button class="box-mon" data-box="${i}"><img src="${sprite(p.id)}" alt="${p.name}"><b>${p.nickname}</b><small>Nv. ${p.level}</small></button>`).join('')||'<p>A Box está vazia.</p>'}</div>`;$('#view-container').onclick=e=>{const send=e.target.closest('[data-sendbox]'),room=e.target.closest('[data-room]'),box=e.target.closest('[data-box]');if(send)return sendToBox(+send.dataset.sendbox);if(room)selectPartner(+room.dataset.room);if(box)boxAction(+box.dataset.box)};hydrateRecoveredNames()}
async function hydrateRecoveredNames(){const pending=state.boxes.filter(p=>p.name.startsWith('Pokémon #'));if(!pending.length)return;let changed=false;await Promise.all(pending.map(async p=>{try{const d=await pokemon(p.id);p.name=d.name;p.nickname=d.name;changed=true}catch{}}));if(changed){persist();if(currentView==='rooms')rooms()}}
function pokeRoom(p,i){return`<article class="poke-room ${p.uid===state.pokemon.uid?'primary-room':''}"><button data-room="${i}"><span>QUARTO ${i+1}</span><img src="${sprite(p.id)}" alt="${p.name}"><b>${p.nickname}</b><small>Nv. ${p.level} · EN ${Math.round(p.energy)}</small></button>${state.active.length>1?`<button class="to-box" data-sendbox="${i}">Enviar à Box</button>`:''}</article>`}
function selectPartner(i){state.pokemon=state.active[i];persist();rooms();toast(`${state.pokemon.nickname} agora é seu parceiro principal.`)}
function sendToBox(i){const p=state.active[i];if(state.active.length<=1)return;if(p.uid===state.pokemon.uid)state.pokemon=state.active[i===0?1:0];state.boxes.push(...state.active.splice(i,1));persist();rooms();toast(`${p.nickname} foi enviado para a Box.`)}
function boxAction(i){if(state.active.length>=6)return toast('Os seis quartos estão ocupados.');const p=state.boxes.splice(i,1)[0];state.active.push(p);persist();rooms();toast(`${p.nickname} ganhou um quarto.`)}
function dex(){$('#view-container').innerHTML=`<div class="view-title"><div><h1>Pokédex</h1><p>${state.caught.length} espécies capturadas · ${state.seen.length} avistadas</p></div></div><div class="dex-grid">${state.seen.map(id=>{const got=state.caught.includes(id);return`<div class="dex-card ${got?'':'unknown'}"><img src="${sprite(id)}" alt=""><b>#${String(id).padStart(4,'0')} ${POKEMON_NAMES[id]||''}</b><small>${got?'Capturado':'Avistado'}</small></div>`}).join('')}</div>`}
async function battleView(){if(!battle){const leader=LEADERS.find((l,i)=>!state.badges.includes(i)&&state.pokemon.level>=l.level-4);$('#view-container').innerHTML=`<div class="view-title"><div><h1>Centro de Batalhas</h1><p>Golpes e efetividade seguem a tipagem oficial.</p></div></div><div class="cards-grid"><article class="battle-card">${itemImg('vs-recorder')}<h2>Treinador visitante</h2><p>Adversário aleatório no seu nível.</p><button class="secondary-button" data-fight="npc">Desafiar</button></article><article class="battle-card">${itemImg('vs-seeker')}<h2>${leader?'Líder '+leader.name:'Próximo ginásio bloqueado'}</h2><p>${leader?'Insígnia '+leader.badge:'Treine mais para desbloquear.'}</p><button class="secondary-button" data-fight="leader" ${leader?'':'disabled'}>${leader?'Entrar no ginásio':'Bloqueado'}</button></article><article class="battle-card">${itemImg('tm-normal')}<h2>Golpes</h2><p>Escolha até quatro golpes aprendidos por nível.</p><button class="secondary-button" id="moves-manage">Organizar golpes</button></article></div>`;$('#view-container').onclick=e=>{const b=e.target.closest('[data-fight]');if(b)startBattle(b.dataset.fight)};$('#moves-manage').onclick=manageMoves;return}drawBattle()}
async function manageMoves(){const p=state.pokemon;toast('Consultando golpes aprendidos...');try{const moves=await movesFor(p),m=$('#modal');$('#modal-content').innerHTML=`<h2>Golpes de ${p.nickname}</h2><p>Selecione até quatro. Disponíveis no nível ${p.level}.</p><div class="move-picker">${moves.map(x=>`<label><input type="checkbox" value="${x.name}" ${(p.moves||[]).includes(x.name)?'checked':''}><b>${x.name}</b><small>${fmt(x.type)} · Poder ${x.power}</small></label>`).join('')}</div><button class="primary-button" id="save-moves">Salvar golpes</button>`;m.showModal();$('#save-moves').onclick=()=>{const picked=[...m.querySelectorAll('input:checked')].map(x=>x.value);if(!picked.length||picked.length>4)return toast('Escolha entre um e quatro golpes.');p.moves=picked;persist();m.close();toast('Golpes atualizados.') }}catch{toast('Não foi possível carregar os golpes.') }}
async function startBattle(type){const p=state.pokemon;if(p.sleepingSince)return toast('Seu parceiro está dormindo.');let enemy;if(type==='leader'){const idx=LEADERS.findIndex((l,i)=>!state.badges.includes(i)&&p.level>=l.level-4);enemy={...LEADERS[idx],leaderIndex:idx}}else{const id=WILD_POOL[Math.floor(Math.random()*WILD_POOL.length)],d=await pokemon(id);enemy={name:'Treinador com '+d.name,id,level:Math.max(3,p.level+Math.floor(Math.random()*5)-2)}}const [pd,ed,pm,em]=await Promise.all([pokemon(p.id),pokemon(enemy.id),movesFor(p),pokemon(enemy.id).then(d=>movesFor({id:enemy.id,level:enemy.level}))]);if(!p.moves?.length)p.moves=pm.slice(-4).map(x=>x.name);battle={enemy,playerData:pd,enemyData:ed,playerMoves:pm.filter(x=>p.moves.includes(x.name)).slice(0,4),enemyMoves:em.slice(-4),playerHp:100,enemyHp:100,log:'A batalha começou!',busy:false};drawBattle()}
function drawBattle(){const p=state.pokemon,e=battle.enemy;$('#view-container').innerHTML=`<div class="view-title"><div><h1>Batalha</h1><p>${battle.playerData.types.map(fmt).join(' / ')} vs ${battle.enemyData.types.map(fmt).join(' / ')}</p></div></div><div class="battle-arena"><div class="fighter"><h3>${p.nickname} · Nv. ${p.level}</h3><div class="hp"><div class="stat-track"><div class="stat-fill" style="width:${battle.playerHp}%"></div></div></div><img src="${sprite(p.id)}" alt="${p.nickname}"></div><div class="fighter"><h3>${e.name} · Nv. ${e.level}</h3><div class="hp"><div class="stat-track"><div class="stat-fill" style="width:${battle.enemyHp}%"></div></div></div><img src="${sprite(e.id)}" alt="adversário"></div></div><div class="battle-log">${battle.log}</div><div class="move-buttons">${battle.playerMoves.map((m,i)=>`<button class="move-button type-${m.type}" data-move="${i}"><b>${m.name}</b><small>${fmt(m.type)} · ${m.power}</small></button>`).join('')}</div><button class="secondary-button" id="flee">Recuar</button>`;$('#view-container').onclick=e=>{const b=e.target.closest('[data-move]');if(b)attack(+b.dataset.move)};$('#flee').onclick=()=>{battle=null;battleView()}}
async function effectiveness(move,defTypes){const chart=await typeChart(move.type);let mult=1;for(const t of defTypes){if(chart.none.includes(t))mult*=0;else if(chart.double.includes(t))mult*=2;else if(chart.half.includes(t))mult*=.5}return mult}
const effectText=m=>m===0?'Sem efeito!':m>=4?'Extremamente efetivo!':m>1?'Super efetivo!':m<1?'Não foi muito efetivo...':'';
async function attack(i){if(battle.busy)return;battle.busy=true;const p=state.pokemon,move=battle.playerMoves[i],mult=await effectiveness(move,battle.enemyData.types),dmg=mult?Math.max(2,Math.round((move.power/5+p.level*1.5+Math.random()*8)*mult)):0;battle.enemyHp=clamp(battle.enemyHp-dmg);battle.log=`${p.nickname} usou ${move.name}! ${effectText(mult)} ${dmg} de dano.`;if(battle.enemyHp<=0)return winBattle();drawBattle();setTimeout(async()=>{const em=battle.enemyMoves[Math.floor(Math.random()*battle.enemyMoves.length)]||{name:'Tackle',type:'normal',power:40},m=await effectiveness(em,battle.playerData.types),d=Math.max(0,Math.round((em.power/6+battle.enemy.level+Math.random()*7)*m));battle.playerHp=clamp(battle.playerHp-d);battle.log=`O rival usou ${em.name}! ${effectText(m)} ${d} de dano.`;battle.busy=false;if(battle.playerHp<=0){p.health=clamp(p.health-15);gainXp(12);persist();toast('Você perdeu, mas ganhou experiência.');battle=null;battleView()}else drawBattle()},650)}
function winBattle(){const e=battle.enemy,reward=e.leaderIndex!==undefined?150:45,xp=e.leaderIndex!==undefined?120:55;state.coins+=reward;gainXp(xp);state.pokemon.ev+=1+(state.furniture.includes('treadmill')?1:0);if(e.leaderIndex!==undefined)state.badges.push(e.leaderIndex);persist();battle=null;toast(`Vitória! +${xp} XP e +${reward} PokéCoins`);battleView()}
function showChangelog(){const m=$('#modal');$('#modal-content').innerHTML=`<h2>Changelog</h2><div class="changelog"><section><b>v2.2 · PokéMart</b><p>Categorias na loja, catálogo completo de itens evolutivos, 18 berries, móveis com bônus de EXP e correções visuais.</p></section><section><b>v2.1 · Jornadas</b><p>Tela de continuar/nova jornada, apelidos na captura e recuperação de Pokémon antigos nas Boxes.</p></section><section><b>v2.0 · Expansão</b><p>Inventário, quartos, Boxes, sono real, encontros offline, captura avançada e golpes oficiais por tipagem.</p></section><section><b>v1.0 · Retro Edition</b><p>Cuidados, minigames, loja, Pokédex, batalhas e clima local.</p></section></div>`;if(!m.open)m.showModal()}
function settings(){const m=$('#modal');$('#modal-content').innerHTML=`<h2>Configurações</h2><div class="settings-list"><p>O jogo salva automaticamente neste navegador.</p><div class="location-notice"><img src="${itemSprite('town-map')}" alt=""> Recomendamos permitir a localização para clima e ciclo local mais precisos.</div><button class="secondary-button" id="weather-refresh">Atualizar tempo local</button><button class="secondary-button" id="open-changelog">Ver changelog</button><button class="danger-button" id="reset-save">Apagar progresso e recomeçar</button></div>`;m.showModal();$('#weather-refresh').onclick=()=>{updateWeather();m.close();toast('Buscando o tempo da sua região...')};$('#open-changelog').onclick=showChangelog;$('#reset-save').onclick=()=>{if(confirm('Apagar todo o progresso?')){clear();location.reload()}}}
$('#modal-close').onclick=()=>$('#modal').close();setInterval(()=>{if(state){for(const p of state.active)updateSleeping(p);generateOfflineEncounters();persist();if(currentView==='home')home()}},30000);window.addEventListener('beforeunload',()=>state&&persist());
showTitle();
