export const STARTERS=[1,4,7,885,39,393,443,215,778,133,25];
export const POKEMON_NAMES={1:'Bulbasaur',4:'Charmander',7:'Squirtle',885:'Dreepy',39:'Jigglypuff',393:'Piplup',443:'Gible',215:'Sneasel',778:'Mimikyu',133:'Eevee',25:'Pikachu'};
export const EVOLUTIONS={1:{level:16,to:2,name:'Ivysaur'},2:{level:32,to:3,name:'Venusaur'},4:{level:16,to:5,name:'Charmeleon'},5:{level:36,to:6,name:'Charizard'},7:{level:16,to:8,name:'Wartortle'},8:{level:36,to:9,name:'Blastoise'},885:{level:50,to:886,name:'Drakloak'},886:{level:60,to:887,name:'Dragapult'},39:{item:'moon-stone',to:40,name:'Wigglytuff'},393:{level:16,to:394,name:'Prinplup'},394:{level:36,to:395,name:'Empoleon'},443:{level:24,to:444,name:'Gabite'},444:{level:48,to:445,name:'Garchomp'},215:{item:'razor-claw',to:461,name:'Weavile'},133:{item:'water-stone',to:134,name:'Vaporeon'},25:{item:'thunder-stone',to:26,name:'Raichu'}};
const evolutionIds=['sun-stone','moon-stone','fire-stone','thunder-stone','water-stone','leaf-stone','shiny-stone','dusk-stone','dawn-stone','oval-stone','kings-rock','metal-coat','dragon-scale','up-grade','protector','electirizer','magmarizer','dubious-disc','reaper-cloth','prism-scale','whipped-dream','sachet','ice-stone','deep-sea-tooth','deep-sea-scale','razor-claw','razor-fang','strawberry-sweet','love-sweet','berry-sweet','clover-sweet','flower-sweet','star-sweet','ribbon-sweet','sweet-apple','tart-apple','cracked-pot','chipped-pot','malicious-armor','syrupy-apple','unremarkable-teacup','masterpiece-teacup','linking-cord','black-augurite','peat-block','metal-alloy'];
const evolutionWithoutSprite=new Set(['strawberry-sweet','love-sweet','berry-sweet','clover-sweet','flower-sweet','star-sweet','ribbon-sweet','sweet-apple','tart-apple','cracked-pot','chipped-pot','malicious-armor','syrupy-apple','unremarkable-teacup','masterpiece-teacup','linking-cord','black-augurite','peat-block','metal-alloy']);
const itemTitle=id=>id.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ');
export const EVOLUTION_ITEMS=evolutionIds.map((id,i)=>({id,...(evolutionWithoutSprite.has(id)?{sprite:'oaks-parcel'}:{}),name:itemTitle(id),price:260+(i%6)*25,desc:'Item oficial usado em evoluções',type:'evolution'}));
export const ITEMS=[
 {id:'razz-berry',name:'Razz Berry',price:26,desc:'Preferida por Pokémon Normal',type:'food',value:20,favored:['normal']},{id:'cheri-berry',name:'Cheri Berry',price:28,desc:'Preferida por Pokémon de Fogo',type:'food',value:20,favored:['fire']},{id:'chesto-berry',name:'Chesto Berry',price:28,desc:'Preferida por Pokémon de Água',type:'food',value:20,favored:['water']},{id:'pecha-berry',name:'Pecha Berry',price:28,desc:'Preferida por Pokémon de Planta',type:'food',value:20,favored:['grass']},{id:'rawst-berry',name:'Rawst Berry',price:28,desc:'Preferida por Pokémon Elétrico',type:'food',value:20,favored:['electric']},{id:'aspear-berry',name:'Aspear Berry',price:28,desc:'Preferida por Pokémon de Gelo',type:'food',value:20,favored:['ice']},{id:'leppa-berry',name:'Leppa Berry',price:30,desc:'Preferida por Pokémon Lutador',type:'food',value:22,favored:['fighting']},{id:'oran-berry',name:'Oran Berry',price:18,desc:'Preferida por Pokémon Venenoso',type:'food',value:18,favored:['poison']},{id:'persim-berry',name:'Persim Berry',price:30,desc:'Preferida por Pokémon Terrestre',type:'food',value:22,favored:['ground']},{id:'lum-berry',name:'Lum Berry',price:45,desc:'Preferida por Pokémon Voador',type:'food',value:25,favored:['flying']},{id:'sitrus-berry',name:'Sitrus Berry',price:35,desc:'Preferida por Pokémon Psíquico',type:'food',value:30,favored:['psychic']},{id:'figy-berry',name:'Figy Berry',price:32,desc:'Preferida por Pokémon Inseto',type:'food',value:24,favored:['bug']},{id:'wiki-berry',name:'Wiki Berry',price:32,desc:'Preferida por Pokémon de Pedra',type:'food',value:24,favored:['rock']},{id:'mago-berry',name:'Mago Berry',price:32,desc:'Preferida por Pokémon Fantasma',type:'food',value:24,favored:['ghost']},{id:'aguav-berry',name:'Aguav Berry',price:35,desc:'Preferida por Pokémon Dragão',type:'food',value:25,favored:['dragon']},{id:'iapapa-berry',name:'Iapapa Berry',price:35,desc:'Preferida por Pokémon Sombrio',type:'food',value:25,favored:['dark']},{id:'bluk-berry',name:'Bluk Berry',price:30,desc:'Preferida por Pokémon de Aço',type:'food',value:22,favored:['steel']},{id:'nanab-berry',name:'Nanab Berry',price:30,desc:'Preferida por Pokémon Fada',type:'food',value:22,favored:['fairy']},
 {id:'poke-ball',name:'Pokébola',price:45,desc:'Bônus de captura ×1',type:'ball',catch:1},{id:'great-ball',name:'Grande Bola',price:90,desc:'Bônus de captura ×1,5',type:'ball',catch:1.5},{id:'ultra-ball',name:'Ultra Bola',price:180,desc:'Bônus de captura ×2',type:'ball',catch:2},{id:'incense',sprite:'odd-incense',name:'Incenso',price:160,desc:'Atrai Pokémon por 30 minutos',type:'utility',duration:1800000},
 {id:'potion',name:'Poção',price:70,desc:'Recupera 20 de saúde',type:'heal',value:20},{id:'super-potion',name:'Super Poção',price:140,desc:'Recupera 50 de saúde',type:'heal',value:50},{id:'hyper-potion',name:'Hiper Poção',price:260,desc:'Recupera 120 de saúde',type:'heal',value:120},{id:'max-potion',name:'Poção Máxima',price:420,desc:'Recupera toda a saúde',type:'heal',value:999},{id:'full-restore',name:'Restauração Total',price:520,desc:'Recupera saúde e todos os status',type:'heal',value:999,full:true},
 {id:'poke-doll',name:'Poké Boneca',price:38,desc:'+20 felicidade',type:'play',value:20},{id:'clefairy-doll',sprite:'poke-doll',name:'Boneca Clefairy',price:65,desc:'+35 felicidade',type:'play',value:35},{id:'soap',sprite:'rage-candy-bar',name:'Sabonete Pokémon',price:25,desc:'+35 higiene',type:'clean',value:35},{id:'lava-cookie',name:'Lava Cookie',price:55,desc:'Limpeza completa',type:'clean',value:100},
 ...EVOLUTION_ITEMS,
 {id:'soft-bed',sprite:'leftovers',name:'Cama Snorlax',price:240,desc:'Reduz o sono completo de 8h para 4h',type:'furniture'},{id:'toy-box',sprite:'poke-doll',name:'Baú de Brinquedos',price:220,desc:'Felicidade cai mais devagar',type:'furniture'},{id:'treadmill',sprite:'macho-brace',name:'Esteira de EV',price:420,desc:'+1 EV após batalhas',type:'furniture'},{id:'training-screen',sprite:'up-grade',name:'Tela de IV',price:600,desc:'Exibe e treina IV',type:'furniture'},
 {id:'study-lamp',sprite:'lucky-egg',name:'Luminária Lucky Egg',price:520,desc:'+10% EXP em todas as atividades',type:'furniture',expBonus:.10},{id:'training-poster',sprite:'exp-share',name:'Painel de Treino',price:380,desc:'+6% EXP em todas as atividades',type:'furniture',expBonus:.06},{id:'berry-planter',sprite:'big-root',name:'Vaso de Berries',price:340,desc:'+4% EXP e ambiente mais natural',type:'furniture',expBonus:.04},{id:'music-player',sprite:'old-amber',name:'Rádio Retrô',price:460,desc:'+7% EXP e melhora o ambiente',type:'furniture',expBonus:.07},{id:'trophy-shelf',sprite:'amulet-coin',name:'Estante de Troféus',price:650,desc:'+12% EXP em todas as atividades',type:'furniture',expBonus:.12}];
export const SHOP=ITEMS;
export const WILD_SPECIES={
  10:{tier:'comum',weight:12,catch:.72},16:{tier:'comum',weight:12,catch:.72},19:{tier:'comum',weight:12,catch:.72,day:true},10091:{tier:'incomum',weight:7,catch:.58,night:true},29:{tier:'comum',weight:10,catch:.68},32:{tier:'comum',weight:10,catch:.68},43:{tier:'comum',weight:11,catch:.7},52:{tier:'comum',weight:10,catch:.68},54:{tier:'comum',weight:9,catch:.65,rain:true},58:{tier:'incomum',weight:6,catch:.52,day:true},63:{tier:'incomum',weight:5,catch:.5},66:{tier:'comum',weight:8,catch:.62},74:{tier:'comum',weight:9,catch:.66},92:{tier:'incomum',weight:9,catch:.56,night:true},109:{tier:'incomum',weight:6,catch:.55},129:{tier:'comum',weight:10,catch:.75,rain:true},172:{tier:'raro',weight:3,catch:.42,storm:true},175:{tier:'incomum',weight:5,catch:.54},183:{tier:'comum',weight:9,catch:.68,rain:true},198:{tier:'incomum',weight:7,catch:.55,night:true},200:{tier:'raro',weight:4,catch:.43,night:true},280:{tier:'incomum',weight:5,catch:.52},300:{tier:'comum',weight:9,catch:.68},333:{tier:'incomum',weight:5,catch:.55,cloudy:true},349:{tier:'raro',weight:3,catch:.4,rain:true},361:{tier:'incomum',weight:7,catch:.52,cold:true},425:{tier:'incomum',weight:7,catch:.54,night:true},447:{tier:'raro',weight:3,catch:.42},459:{tier:'raro',weight:4,catch:.42,cold:true},519:{tier:'comum',weight:10,catch:.68,day:true},582:{tier:'incomum',weight:6,catch:.5,cold:true},607:{tier:'incomum',weight:8,catch:.52,night:true},633:{tier:'muito-raro',weight:1,catch:.24,night:true},659:{tier:'comum',weight:10,catch:.7,day:true},661:{tier:'comum',weight:10,catch:.7,day:true},704:{tier:'raro',weight:3,catch:.4,rain:true},742:{tier:'comum',weight:9,catch:.68,day:true},819:{tier:'comum',weight:11,catch:.72,day:true},840:{tier:'incomum',weight:6,catch:.55},885:{tier:'muito-raro',weight:1,catch:.22,night:true},147:{tier:'muito-raro',weight:1,catch:.2},246:{tier:'muito-raro',weight:1,catch:.2},443:{tier:'muito-raro',weight:1,catch:.2}
};
export const WILD_POOL=Object.keys(WILD_SPECIES).map(Number);
export const LEADERS=[{name:'Brock',id:95,level:12,badge:'Rocha'},{name:'Misty',id:121,level:20,badge:'Cascata'},{name:'Lt. Surge',id:26,level:28,badge:'Trovão'},{name:'Erika',id:45,level:36,badge:'Arco-íris'}];
export const GAME_COSTS={berry:20,memory:25,timing:30};
export const sprite=id=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
export const itemSprite=id=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/${ITEMS.find(i=>i.id===id)?.sprite||id}.png`;
export const coinSprite='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/coin-case.png';
export const shinySprite=id=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/${id}.png`;
export const furnitureSprite=id=>`assets/furniture/${id}.png`;
