export const STARTERS=[1,4,7,885,39,393,443,215,778,133,25];
export const POKEMON_NAMES={1:'Bulbasaur',4:'Charmander',7:'Squirtle',885:'Dreepy',39:'Jigglypuff',393:'Piplup',443:'Gible',215:'Sneasel',778:'Mimikyu',133:'Eevee',25:'Pikachu'};
export const EVOLUTIONS={1:{level:16,to:2,name:'Ivysaur'},2:{level:32,to:3,name:'Venusaur'},4:{level:16,to:5,name:'Charmeleon'},5:{level:36,to:6,name:'Charizard'},7:{level:16,to:8,name:'Wartortle'},8:{level:36,to:9,name:'Blastoise'},885:{level:50,to:886,name:'Drakloak'},886:{level:60,to:887,name:'Dragapult'},39:{item:'moon-stone',to:40,name:'Wigglytuff'},393:{level:16,to:394,name:'Prinplup'},394:{level:36,to:395,name:'Empoleon'},443:{level:24,to:444,name:'Gabite'},444:{level:48,to:445,name:'Garchomp'},215:{item:'razor-claw',to:461,name:'Weavile'},133:{item:'water-stone',to:134,name:'Vaporeon'},25:{item:'thunder-stone',to:26,name:'Raichu'}};
const evolutionIds=['sun-stone','moon-stone','fire-stone','thunder-stone','water-stone','leaf-stone','shiny-stone','dusk-stone','dawn-stone','oval-stone','kings-rock','metal-coat','dragon-scale','up-grade','protector','electirizer','magmarizer','dubious-disc','reaper-cloth','prism-scale','whipped-dream','sachet','ice-stone','deep-sea-tooth','deep-sea-scale','razor-claw','razor-fang','strawberry-sweet','love-sweet','berry-sweet','clover-sweet','flower-sweet','star-sweet','ribbon-sweet','sweet-apple','tart-apple','cracked-pot','chipped-pot','malicious-armor','syrupy-apple','unremarkable-teacup','masterpiece-teacup','linking-cord','black-augurite','peat-block','metal-alloy'];
const evolutionWithoutSprite=new Set(['strawberry-sweet','love-sweet','berry-sweet','clover-sweet','flower-sweet','star-sweet','ribbon-sweet','sweet-apple','tart-apple','cracked-pot','chipped-pot','malicious-armor','syrupy-apple','unremarkable-teacup','masterpiece-teacup','linking-cord','black-augurite','peat-block','metal-alloy']);
const itemTitle=id=>id.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ');
export const EVOLUTION_ITEMS=evolutionIds.map((id,i)=>({id,...(evolutionWithoutSprite.has(id)?{sprite:'oaks-parcel'}:{}),name:itemTitle(id),price:260+(i%6)*25,desc:'Item oficial usado em evoluções',type:'evolution'}));
export const ITEMS=[
 {id:'razz-berry',name:'Razz Berry',price:26,desc:'Preferida por Pokémon Normal',type:'food',value:20,favored:['normal']},{id:'cheri-berry',name:'Cheri Berry',price:28,desc:'Preferida por Pokémon de Fogo',type:'food',value:20,favored:['fire']},{id:'chesto-berry',name:'Chesto Berry',price:28,desc:'Preferida por Pokémon de Água',type:'food',value:20,favored:['water']},{id:'pecha-berry',name:'Pecha Berry',price:28,desc:'Preferida por Pokémon de Planta',type:'food',value:20,favored:['grass']},{id:'rawst-berry',name:'Rawst Berry',price:28,desc:'Preferida por Pokémon Elétrico',type:'food',value:20,favored:['electric']},{id:'aspear-berry',name:'Aspear Berry',price:28,desc:'Preferida por Pokémon de Gelo',type:'food',value:20,favored:['ice']},{id:'leppa-berry',name:'Leppa Berry',price:30,desc:'Preferida por Pokémon Lutador',type:'food',value:22,favored:['fighting']},{id:'oran-berry',name:'Oran Berry',price:18,desc:'Preferida por Pokémon Venenoso',type:'food',value:18,favored:['poison']},{id:'persim-berry',name:'Persim Berry',price:30,desc:'Preferida por Pokémon Terrestre',type:'food',value:22,favored:['ground']},{id:'lum-berry',name:'Lum Berry',price:45,desc:'Preferida por Pokémon Voador',type:'food',value:25,favored:['flying']},{id:'sitrus-berry',name:'Sitrus Berry',price:35,desc:'Preferida por Pokémon Psíquico',type:'food',value:30,favored:['psychic']},{id:'figy-berry',name:'Figy Berry',price:32,desc:'Preferida por Pokémon Inseto',type:'food',value:24,favored:['bug']},{id:'wiki-berry',name:'Wiki Berry',price:32,desc:'Preferida por Pokémon de Pedra',type:'food',value:24,favored:['rock']},{id:'mago-berry',name:'Mago Berry',price:32,desc:'Preferida por Pokémon Fantasma',type:'food',value:24,favored:['ghost']},{id:'aguav-berry',name:'Aguav Berry',price:35,desc:'Preferida por Pokémon Dragão',type:'food',value:25,favored:['dragon']},{id:'iapapa-berry',name:'Iapapa Berry',price:35,desc:'Preferida por Pokémon Sombrio',type:'food',value:25,favored:['dark']},{id:'bluk-berry',name:'Bluk Berry',price:30,desc:'Preferida por Pokémon de Aço',type:'food',value:22,favored:['steel']},{id:'nanab-berry',name:'Nanab Berry',price:30,desc:'Preferida por Pokémon Fada',type:'food',value:22,favored:['fairy']},
 {id:'poke-ball',name:'Pokébola',price:45,desc:'Bônus de captura ×1',type:'ball',catch:1},{id:'great-ball',name:'Grande Bola',price:90,desc:'Bônus de captura ×1,5',type:'ball',catch:1.5},{id:'ultra-ball',name:'Ultra Bola',price:180,desc:'Bônus de captura ×2',type:'ball',catch:2},
 {id:'poke-doll',name:'Poké Boneca',price:38,desc:'+20 felicidade',type:'play',value:20},{id:'clefairy-doll',sprite:'poke-doll',name:'Boneca Clefairy',price:65,desc:'+35 felicidade',type:'play',value:35},{id:'soap',sprite:'rage-candy-bar',name:'Sabonete Pokémon',price:25,desc:'+35 higiene',type:'clean',value:35},{id:'lava-cookie',name:'Lava Cookie',price:55,desc:'Limpeza completa',type:'clean',value:100},
 ...EVOLUTION_ITEMS,
 {id:'soft-bed',sprite:'leftovers',name:'Cama Snorlax',price:240,desc:'Melhora o quarto',type:'furniture'},{id:'toy-box',sprite:'poke-doll',name:'Baú de Brinquedos',price:220,desc:'Felicidade cai mais devagar',type:'furniture'},{id:'treadmill',sprite:'macho-brace',name:'Esteira de EV',price:420,desc:'+1 EV após batalhas',type:'furniture'},{id:'training-screen',sprite:'up-grade',name:'Tela de IV',price:600,desc:'Exibe e treina IV',type:'furniture'},
 {id:'study-lamp',sprite:'lucky-egg',name:'Luminária Lucky Egg',price:520,desc:'+10% EXP em todas as atividades',type:'furniture',expBonus:.10},{id:'training-poster',sprite:'exp-share',name:'Painel de Treino',price:380,desc:'+6% EXP em todas as atividades',type:'furniture',expBonus:.06},{id:'berry-planter',sprite:'big-root',name:'Vaso de Berries',price:340,desc:'+4% EXP e ambiente mais natural',type:'furniture',expBonus:.04},{id:'music-player',sprite:'old-amber',name:'Rádio Retrô',price:460,desc:'+7% EXP e música para o quarto',type:'furniture',expBonus:.07},{id:'trophy-shelf',sprite:'amulet-coin',name:'Estante de Troféus',price:650,desc:'+12% EXP em todas as atividades',type:'furniture',expBonus:.12}];
export const SHOP=ITEMS;
export const WILD_POOL=[10,16,19,29,32,43,52,54,58,63,66,74,92,109,129,172,175,183,198,200,280,300,333,349,425,447,519,659,661,704,742,819,840,885,147,246,443,607,633];
export const LEADERS=[{name:'Brock',id:95,level:12,badge:'Rocha'},{name:'Misty',id:121,level:20,badge:'Cascata'},{name:'Lt. Surge',id:26,level:28,badge:'Trovão'},{name:'Erika',id:45,level:36,badge:'Arco-íris'}];
export const GAME_COSTS={berry:12,memory:16,timing:22};
export const sprite=id=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
export const itemSprite=id=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/${ITEMS.find(i=>i.id===id)?.sprite||id}.png`;
export const coinSprite='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/coin-case.png';
