export const STARTERS=[1,4,7,885,39,393,443,215,778,133,25];
export const POKEMON_NAMES={1:'Bulbasaur',4:'Charmander',7:'Squirtle',885:'Dreepy',39:'Jigglypuff',393:'Piplup',443:'Gible',215:'Sneasel',778:'Mimikyu',133:'Eevee',25:'Pikachu'};
export const EVOLUTIONS={1:{level:16,to:2,name:'Ivysaur'},2:{level:32,to:3,name:'Venusaur'},4:{level:16,to:5,name:'Charmeleon'},5:{level:36,to:6,name:'Charizard'},7:{level:16,to:8,name:'Wartortle'},8:{level:36,to:9,name:'Blastoise'},885:{level:50,to:886,name:'Drakloak'},886:{level:60,to:887,name:'Dragapult'},39:{item:'moon-stone',to:40,name:'Wigglytuff'},393:{level:16,to:394,name:'Prinplup'},394:{level:36,to:395,name:'Empoleon'},443:{level:24,to:444,name:'Gabite'},444:{level:48,to:445,name:'Garchomp'},215:{item:'razor-claw',to:461,name:'Weavile'},133:{item:'water-stone',to:134,name:'Vaporeon'},25:{item:'thunder-stone',to:26,name:'Raichu'}};
export const ITEMS=[
 {id:'oran-berry',name:'Oran Berry',price:18,desc:'+18 fome',type:'food',value:18,favored:['water','ice']},{id:'sitrus-berry',name:'Sitrus Berry',price:35,desc:'+30 fome e +5 saúde',type:'food',value:30,favored:['fire','dragon']},{id:'cheri-berry',name:'Cheri Berry',price:28,desc:'Favorita de Fogo e Elétrico',type:'food',value:20,favored:['fire','electric']},{id:'chesto-berry',name:'Chesto Berry',price:28,desc:'Favorita de Água e Psíquico',type:'food',value:20,favored:['water','psychic']},{id:'pecha-berry',name:'Pecha Berry',price:28,desc:'Favorita de Fada e Planta',type:'food',value:20,favored:['fairy','grass']},
 {id:'poke-ball',name:'Pokébola',price:45,desc:'Bônus de captura ×1',type:'ball',catch:1},{id:'great-ball',name:'Grande Bola',price:90,desc:'Bônus de captura ×1,5',type:'ball',catch:1.5},{id:'ultra-ball',name:'Ultra Bola',price:180,desc:'Bônus de captura ×2',type:'ball',catch:2},
 {id:'poke-doll',name:'Poké Boneca',price:38,desc:'+20 felicidade',type:'play',value:20},{id:'clefairy-doll',name:'Boneca Clefairy',price:65,desc:'+35 felicidade',type:'play',value:35},{id:'soap',sprite:'rage-candy-bar',name:'Sabonete Pokémon',price:25,desc:'+35 higiene',type:'clean',value:35},{id:'lava-cookie',name:'Lava Cookie',price:55,desc:'Limpeza completa',type:'clean',value:100},
 {id:'thunder-stone',name:'Pedra do Trovão',price:280,desc:'Item de evolução',type:'evolution'},{id:'water-stone',name:'Pedra da Água',price:280,desc:'Item de evolução',type:'evolution'},{id:'moon-stone',name:'Pedra da Lua',price:280,desc:'Item de evolução',type:'evolution'},{id:'razor-claw',name:'Garra Afiada',price:320,desc:'Item raro de evolução',type:'evolution'},
 {id:'soft-bed',sprite:'leftovers',name:'Cama Snorlax',price:240,desc:'Melhora o quarto',type:'furniture'},{id:'toy-box',sprite:'poke-doll',name:'Baú de Brinquedos',price:220,desc:'Felicidade cai mais devagar',type:'furniture'},{id:'treadmill',sprite:'macho-brace',name:'Esteira de EV',price:420,desc:'+1 EV após batalhas',type:'furniture'},{id:'training-screen',sprite:'upgrade',name:'Tela de IV',price:600,desc:'Exibe e treina IV',type:'furniture'}];
export const SHOP=ITEMS;
export const WILD_POOL=[10,16,19,29,32,43,52,54,58,63,66,74,92,109,129,172,175,183,198,200,280,300,333,349,425,447,519,659,661,704,742,819,840,885,147,246,443,607,633];
export const LEADERS=[{name:'Brock',id:95,level:12,badge:'Rocha'},{name:'Misty',id:121,level:20,badge:'Cascata'},{name:'Lt. Surge',id:26,level:28,badge:'Trovão'},{name:'Erika',id:45,level:36,badge:'Arco-íris'}];
export const GAME_COSTS={berry:12,memory:16,timing:22};
export const sprite=id=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
export const itemSprite=id=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/${ITEMS.find(i=>i.id===id)?.sprite||id}.png`;
export const coinSprite='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/coin-case.png';
