const KEY='pokegotchi-save-v2',OLD='pokeninho-save-v1';
export const creature=(id,name,nickname,level=5)=>({uid:`p${id}-${Date.now()}-${Math.random().toString(16).slice(2)}`,id,name,nickname,level,xp:0,health:100,hunger:86,energy:82,happiness:88,hygiene:90,iv:Math.floor(Math.random()*11)+20,ev:0,sleepingSince:null,moves:[]});
export function load(){try{const raw=localStorage.getItem(KEY)||localStorage.getItem(OLD);if(!raw)return null;return migrate(JSON.parse(raw))}catch{return null}}
export function save(state){state.lastSaved=Date.now();localStorage.setItem(KEY,JSON.stringify(state))}
export function clear(){localStorage.removeItem(KEY);localStorage.removeItem(OLD)}
export function fresh(id,nickname,name){const first=creature(id,name,nickname);return{version:2,lastSaved:Date.now(),createdAt:Date.now(),pokemon:first,active:[first],boxes:[],coins:180,inventory:{'poke-ball':5,'oran-berry':3,'poke-doll':2,'soap':2},furniture:[],caught:[id],seen:[id],badges:[],nextSpawn:Date.now()+600000,encounters:[],weather:{code:0,temp:null,label:'Céu limpo',icon:'clear',day:true,source:'estimado'},dailyClaim:0}}
function migrate(s){if(s.version===2){s.active=s.active||[s.pokemon];s.boxes=s.boxes||[];s.encounters=s.encounters||[];return s}const p={...creature(s.pokemon.id,s.pokemon.name,s.pokemon.nickname,s.pokemon.level),...s.pokemon};const inv={...s.inventory};if(inv.oran){inv['oran-berry']=(inv['oran-berry']||0)+inv.oran;delete inv.oran}if(inv.sitrus){inv['sitrus-berry']=(inv['sitrus-berry']||0)+inv.sitrus;delete inv.sitrus}return{...s,version:2,pokemon:p,active:[p],boxes:[],encounters:s.wild?[s.wild]:[],inventory:inv,nextSpawn:Math.max(Date.now()+60000,s.nextSpawn||0)}}
export function addCreature(state,data){const p=creature(data.id,data.name,data.name,Math.max(3,Math.floor((state.pokemon.level+data.rarity*10)/2)));if(state.active.length<6)state.active.push(p);else state.boxes.push(p);state.caught=[...new Set([...state.caught,p.id])];return p}
export function applyOffline(s){const now=Date.now(),mins=Math.min((now-(s.lastSaved||now))/60000,1440);for(const p of s.active){if(p.sleepingSince){p.energy=Math.min(100,p.energy+(now-Math.max(s.lastSaved||now,p.sleepingSince))/288000);if(p.energy>=100)p.sleepingSince=null}else{p.hunger=Math.max(0,p.hunger-mins*.08);p.happiness=Math.max(0,p.happiness-mins*(s.furniture.includes('toy-box')?.018:.03));p.hygiene=Math.max(0,p.hygiene-mins*.025)}}return mins>=1?Math.floor(mins):null}
