const KEY='pokegotchi-save-v2',OLD='pokeninho-save-v1';
const genderFor=(id,rate=null)=>Number(id)===132||rate===-1?'genderless':rate===0?'male':rate===8?'female':Math.random()*8<(Number.isFinite(rate)?rate:4)?'female':'male';
export const creature=(id,name,nickname,level=5,shiny=false,gender=null,genderRate=null)=>({uid:`p${id}-${Date.now()}-${Math.random().toString(16).slice(2)}`,id,name,nickname,level,xp:0,health:100,hunger:86,energy:82,happiness:88,hygiene:90,friendship:70,iv:Math.floor(Math.random()*11)+20,ev:0,shiny,gender:gender||(Number.isFinite(genderRate)?genderFor(id,genderRate):null),genderNeedsHydration:!gender&&!Number.isFinite(genderRate),sleepingSince:null,moves:[]});
export function load(){try{const raw=localStorage.getItem(KEY)||localStorage.getItem(OLD);if(!raw)return null;const s=recoverCaptured(migrate(JSON.parse(raw)));s.version=9;s.cryVolume=Number.isFinite(s.cryVolume)?s.cryVolume:.28;s.breeding=s.breeding||null;s.expeditions=Array.isArray(s.expeditions)?s.expeditions:s.expedition?[s.expedition]:[];s.expedition=null;for(const exp of s.expeditions){exp.expeditionId=exp.expeditionId||`legacy-${exp.startedAt||Date.now()}`;exp.reward=exp.reward||{xp:0,coins:0,items:{}}}for(const p of [...s.active,...s.boxes])if(!p.gender){p.gender=genderFor(p.id);p.genderNeedsHydration=true}return s}catch{return null}}
export function save(state){state.lastSaved=Date.now();localStorage.setItem(KEY,JSON.stringify(state))}
export function clear(){localStorage.removeItem(KEY);localStorage.removeItem(OLD)}
export function fresh(id,nickname,name,trainerName='Treinador'){const first=creature(id,name,nickname);return{version:9,recoveredLegacy:true,lastSaved:Date.now(),createdAt:Date.now(),trainerName,trainerTitle:null,pokemon:first,active:[first],boxes:[],coins:180,inventory:{'poke-ball':5,'oran-berry':3,'poke-doll':2,'soap':2,'incense':1,'potion':2},furniture:[],storedFurniture:[],furniturePositions:{},redeemedCodes:[],caught:[id],seen:[id],badges:[],nextSpawn:Date.now()+600000,encounters:[],incenseUntil:0,soundEnabled:true,cryVolume:.28,breeding:null,weather:{code:0,temp:null,label:'Céu limpo',icon:'clear',day:true,source:'estimado'},dailyClaim:0,expedition:null,expeditions:[],rescueCenter:[],expeditionHistory:[],eventStats:{rescued:0,greatSuccess:0,collections:{},labTypes:[]}}}
function migrate(s){if(s.version>=2){s.version=7;s.active=s.active||[s.pokemon];s.boxes=s.boxes||[];s.encounters=s.encounters||[];s.incenseUntil=s.incenseUntil||0;s.soundEnabled=s.soundEnabled!==false;s.furniturePositions=s.furniturePositions||{};s.storedFurniture=s.storedFurniture||[];s.redeemedCodes=s.redeemedCodes||[];s.trainerTitle=s.trainerTitle||null;s.rescueCenter=s.rescueCenter||[];s.expeditionHistory=s.expeditionHistory||[];s.eventStats=s.eventStats||{rescued:0,greatSuccess:0,collections:{},labTypes:[]};for(const p of [...s.active,...s.boxes]){p.shiny=!!p.shiny;p.friendship=Number.isFinite(p.friendship)?p.friendship:70;p.iv=Number.isFinite(p.iv)?p.iv:Math.floor(Math.random()*11)+20;p.ev=Number.isFinite(p.ev)?p.ev:0}return s}const p={...creature(s.pokemon.id,s.pokemon.name,s.pokemon.nickname,s.pokemon.level),...s.pokemon};const inv={...s.inventory};if(inv.oran){inv['oran-berry']=(inv['oran-berry']||0)+inv.oran;delete inv.oran}if(inv.sitrus){inv['sitrus-berry']=(inv['sitrus-berry']||0)+inv.sitrus;delete inv.sitrus}return{...s,version:7,recoveredLegacy:false,pokemon:p,active:[p],boxes:[],encounters:s.wild?[s.wild]:[],inventory:inv,furniturePositions:{},storedFurniture:[],redeemedCodes:[],trainerTitle:null,expedition:null,rescueCenter:[],expeditionHistory:[],eventStats:{rescued:0,greatSuccess:0,collections:{},labTypes:[]},incenseUntil:0,soundEnabled:true,nextSpawn:Math.max(Date.now()+60000,s.nextSpawn||0)}}
function recoverCaptured(s){if(!s.recoveredLegacy){const owned=new Set([...s.active,...s.boxes].map(p=>p.id));for(const id of s.caught||[]){if(!owned.has(id)){s.boxes.push(creature(id,`Pokémon #${id}`,`Pokémon #${id}`,Math.max(3,s.pokemon.level-2)));owned.add(id)}}s.recoveredLegacy=true}const primary=s.active.find(p=>p.uid===s.pokemon?.uid)||s.active.find(p=>p.id===s.pokemon?.id&&p.nickname===s.pokemon?.nickname)||s.active[0];if(primary)s.pokemon=primary;s.encounters=(s.encounters||[]).map(e=>({...e,shiny:!!e.shiny,fed:e.fed||null,selectedBall:e.selectedBall||null}));return s}
export function addCreature(state,data,nickname=data.name){const p=creature(data.id,data.name,nickname,Math.max(3,state.pokemon.level+Math.floor(Math.random()*3)-1),!!data.shiny,data.gender,data.genderRate);if(state.active.length<6)state.active.push(p);else state.boxes.push(p);state.caught=[...new Set([...state.caught,p.id])];return p}
export function applyOfflineSafe(s){const active=s.active,away=new Set((s.expeditions||[]).map(exp=>exp.pokemonUid));s.active=active.filter(p=>!away.has(p.uid));const elapsed=applyOffline(s);s.active=active;return elapsed}
export function applyOffline(s){const now=Date.now(),from=Math.min(now,s.lastSaved||now),mins=Math.min((now-from)/60000,10080);if(mins<=0)return null;for(const p of s.active){if(s.expedition?.pokemonUid===p.uid)continue;const sleeping=Number.isFinite(p.sleepingSince)&&p.sleepingSince>0,restFactor=sleeping?.5:1;if(sleeping){const fullMs=s.furniture.includes('soft-bed')?14400000:28800000;if(!Number.isFinite(p.sleepEnergyStart))p.sleepEnergyStart=Math.max(0,p.energy-Math.max(0,from-p.sleepingSince)/fullMs*100);p.energy=Math.min(100,p.sleepEnergyStart+Math.max(0,now-p.sleepingSince)/fullMs*100)}else p.energy=Math.max(0,p.energy-mins*.10);p.hunger=Math.max(0,p.hunger-mins*.14*restFactor);p.happiness=Math.max(0,p.happiness-mins*(s.furniture.includes('toy-box')?.045:.065)*restFactor);p.hygiene=Math.max(0,p.hygiene-mins*.05*restFactor);if(p.hunger<=0||p.hygiene<=0)p.health=Math.max(0,p.health-mins*.04);const critical=[p.hunger,p.energy,p.health].filter(v=>v<25).length;if(critical)p.friendship=Math.max(0,(p.friendship??70)-mins*.018*critical*restFactor)}return mins>=1?Math.floor(mins):null}
